### Phik-matrix -> Associations

Associations measure the strength of assocation between two variables. While correlations only measure LINEAR connection, associations can also handle non-linear connections. See "associations_vs_correlations.ipynb" for a simple comparison where associations are usually more useful.

**NOTE!** You can see both the correlations and associations at the asme time if you use SweetViz or Dython! You can also have correlations/phik-matrix in ydata at the same time, if you configure it correctly.

In [1]:
# if phik-matrix not found in pandas, try:
# pip install phik
import phik
import pandas as pd

# load data
df = pd.read_csv("../lifestyle_sustainability_data_processed.csv")

# compute phik-matrix values
phik_matrix = df.phik_matrix()

phik_matrix

interval columns not set, guessing: ['Age', 'LocalFoodFrequency', 'HomeSize', 'ClothingFrequency', 'SustainableBrands', 'EnvironmentalAwareness', 'CommunityInvolvement', 'MonthlyElectricityConsumption', 'MonthlyWaterConsumption', 'UsingPlasticProducts', 'PhysicalActivities', 'Rating', 'Location_Rural', 'Location_Suburban', 'Location_Urban', 'DietType_Balanced', 'DietType_Mostly Animal-Based', 'TransportationMode_Bike', 'TransportationMode_Car', 'TransportationMode_Public Transit', 'EnergySource_Mixed', 'EnergySource_Non-Renewable', 'HomeType_Apartment', 'HomeType_House', 'Gender_Female', 'Gender_Male', 'Gender_Non-Binary', 'DisposalMethods_Combination', 'DisposalMethods_Composting', 'DisposalMethods_Landfill']

,Age,LocalFoodFrequency,HomeSize,ClothingFrequency,SustainableBrands,EnvironmentalAwareness,CommunityInvolvement,MonthlyElectricityConsumption,MonthlyWaterConsumption,UsingPlasticProducts,...,EnergySource_Mixed,EnergySource_Non-Renewable,HomeType_Apartment,HomeType_House,Gender_Female,Gender_Male,Gender_Non-Binary,DisposalMethods_Combination,DisposalMethods_Composting,DisposalMethods_Landfill
Age,1.000000,0.438503,0.323545,0.317462,0.268559,0.427044,0.351800,0.394956,0.427426,0.334749,...,0.242232,0.202629,0.153891,0.149939,0.057554,0.092349,0.107921,0.272715,0.156047,0.252226
LocalFoodFrequency,0.438503,1.000000,0.432782,0.771051,0.632702,0.476862,0.345311,0.577687,0.595472,0.702611,...,0.570121,0.659845,0.000000,0.132728,0.388216,0.406067,0.125132,0.372228,0.420650,0.694070
HomeSize,0.323545,0.432782,1.000000,0.465113,0.421459,0.548723,0.336965,0.664936,0.611203,0.527164,...,0.246587,0.203611,0.700265,0.720385,0.302251,0.265174,0.113628,0.353878,0.467599,0.330876
ClothingFrequency,0.317462,0.771051,0.465113,1.000000,0.484206,0.456956,0.363092,0.572365,0.543111,0.697936,...,0.487379,0.592064,0.155066,0.170423,0.478546,0.421783,0.192340,0.384014,0.647342,0.596323
SustainableBrands,0.268559,0.632702,0.421459,0.484206,1.000000,0.381923,0.128249,0.671948,0.603893,0.633976,...,0.145484,0.636902,0.000000,0.152943,0.452282,0.242064,0.195172,0.194069,0.324633,0.692635
EnvironmentalAwareness,0.427044,0.476862,0.548723,0.456956,0.381923,1.000000,0.450300,0.778082,0.745685,0.404139,...,0.331833,0.406538,0.094358,0.106258,0.266685,0.199059,0.052508,0.290451,0.239109,0.414822
CommunityInvolvement,0.351800,0.345311,0.336965,0.363092,0.128249,0.450300,1.000000,0.512757,0.544926,0.215637,...,0.175374,0.088152,0.035819,0.036141,0.147217,0.152239,0.000000,0.160516,0.223628,0.050130
MonthlyElectricityConsumption,0.394956,0.577687,0.664936,0.572365,0.671948,0.778082,0.512757,1.000000,0.821709,0.667606,...,0.606430,0.665538,0.326859,0.327172,0.497368,0.434181,0.292925,0.508353,0.574646,0.650404
MonthlyWaterConsumption,0.427426,0.595472,0.611203,0.543111,0.603893,0.745685,0.544926,0.821709,1.000000,0.684472,...,0.545134,0.687907,0.300628,0.217601,0.372200,0.389189,0.000000,0.433288,0.549559,0.795324
UsingPlasticProducts,0.334749,0.702611,0.527164,0.697936,0.633976,0.404139,0.215637,0.667606,0.684472,1.000000,...,0.462872,0.738152,0.308143,0.242486,0.532698,0.339417,0.307595,0.509795,0.731350,0.844186
PhysicalActivities,0.447113,0.327496,0.510533,0.333505,0.204711,0.435960,0.711786,0.690701,0.644891,0.459998,...,0.212347,0.192285,0.122956,0.054125,0.168294,0.116961,0.052418,0.156220,0.242408,0.201668
Rating,0.357638,0.469078,0.451047,0.438675,0.431190,0.806472,0.495517,0.754159,0.744843,0.493330,...,0.362023,0.502949,0.092934,0.071909,0.268883,0.227619,0.102238,0.255950,0.382957,0.553674
Location_Rural,0.446405,0.234011,0.429268,0.354984,0.000000,0.203867,0.000000,0.386817,0.490326,0.337027,...,0.056737,0.145143,0.318960,0.214787,0.000000,0.000000,0.000000,0.446280,0.248946,0.121489
Location_Suburban,0.340910,0.413675,0.378380,0.611220,0.208628,0.205145,0.104079,0.367951,0.420168,0.318612,...,0.000000,0.268597,0.000000,0.087246,0.000000,0.060414,0.000000,0.241980,0.000000,0.268209
Location_Urban,0.383829,0.262663,0.432617,0.304816,0.162004,0.206815,0.070081,0.303274,0.365550,0.209611,...,0.000000,0.081164,0.230170,0.316621,0.000000,0.024424,0.000000,0.178786,0.169708,0.105530
DietType_Balanced,0.310810,0.450299,0.390664,0.366004,0.000000,0.154676,0.201863,0.532130,0.507043,0.635589,...,0.255553,0.043664,0.223229,0.126889,0.000000,0.000000,0.131702,0.000000,0.152724,0.230399
DietType_Mostly Animal-Based,0.262212,0.684912,0.279663,0.612480,0.632236,0.305545,0.007719,0.623956,0.561351,0.678569,...,0.206427,0.560317,0.000000,0.108810,0.418601,0.230709,0.215864,0.226925,0.297661,0.693358
TransportationMode_Bike,0.101099,0.222782,0.165386,0.236150,0.142818,0.242368,0.000000,0.346644,0.290955,0.219800,...,0.129609,0.240640,0.125431,0.000000,0.184648,0.110381,0.000000,0.301617,0.277298,0.301339
TransportationMode_Car,0.261730,0.638785,0.353379,0.632487,0.646448,0.404048,0.030887,0.635702,0.659660,0.725401,...,0.293682,0.708293,0.000000,0.057748,0.333397,0.224010,0.014125,0.271115,0.219185,0.742842
TransportationMode_Public Transit,0.194373,0.318343,0.381095,0.417972,0.186350,0.169330,0.108211,0.560916,0.558006,0.639610,...,0.269047,0.335185,0.301021,0.000000,0.052402,0.000000,0.000000,0.123085,0.309623,0.267914
EnergySource_Mixed,0.242232,0.570121,0.246587,0.487379,0.145484,0.331833,0.175374,0.606430,0.545134,0.462872,...,1.000000,0.657431,0.000000,0.000000,0.030123,0.061432,0.000000,0.516762,0.286405,0.355410
EnergySource_Non-Renewable,0.202629,0.659845,0.203611,0.592064,0.636902,0.406538,0.088152,0.665538,0.687907,0.738152,...,0.657431,1.000000,0.000000,0.147865,0.434672,0.272658,0.126791,0.194112,0.213225,0.735569
HomeType_Apartment,0.153891,0.000000,0.700265,0.155066,0.000000,0.094358,0.035819,0.326859,0.300628,0.308143,...,0.000000,0.000000,1.000000,0.813181,0.043236,0.000000,0.050158,0.075585,0.012442,0.112073
HomeType_House,0.149939,0.132728,0.720385,0.170423,0.152943,0.106258,0.036141,0.327172,0.217601,0.242486,...,0.000000,0.147865,0.813181,1.000000,0.116884,0.034361,0.000000,0.088203,0.000000,0.000000
Gender_Female,0.057554,0.388216,0.302251,0.478546,0.452282,0.266685,0.147217,0.497368,0.372200,0.532698,...,0.030123,0.434672,0.043236,0.116884,1.000000,0.726464,0.458835,0.000000,0.311524,0.337449
Gender_Male,0.092349,0.406067,0.265174,0.421783,0.242064,0.199059,0.152239,0.434181,0.389189,0.339417,...,0.061432,0.272658,0.000000,0.034361,0.726464,1.000000,0.476820,0.000000,0.235327,0.305989
Gender_Non-Binary,0.107921,0.125132,0.113628,0.192340,0.195172,0.052508,0.000000,0.292925,0.000000,0.307595,...,0.000000,0.126791,0.050158,0.000000,0.458835,0.476820,1.000000,0.000000,0.133019,0.079859
DisposalMethods_Combination,0.272715,0.372228,0.353878,0.384014,0.194069,0.290451,0.160516,0.508353,0.433288,0.509795,...,0.516762,0.194112,0.075585,0.088203,0.000000,0.000000,0.000000,1.000000,0.394643,0.430534
DisposalMethods_Composting,0.156047,0.420650,0.467599,0.647342,0.324633,0.239109,0.223628,0.574646,0.549559,0.731350,...,0.286405,0.213225,0.012442,0.000000,0.311524,0.235327,0.133019,0.394643,1.000000,0.526853
DisposalMethods_Landfill,0.252226,0.694070,0.330876,0.596323,0.692635,0.414822,0.050130,0.650404,0.795324,0.844186,...,0.355410,0.735569,0.112073,0.000000,0.337449,0.305989,0.079859,0.430534,0.526853,1.000000

In [2]:
phik_matrix['Rating'].sort_values(ascending=False)

Rating                               1.000000
EnvironmentalAwareness               0.806472
MonthlyElectricityConsumption        0.754159
MonthlyWaterConsumption              0.744843
DisposalMethods_Landfill             0.553674
TransportationMode_Car               0.542625
EnergySource_Non-Renewable           0.502949
CommunityInvolvement                 0.495517
UsingPlasticProducts                 0.493330
DietType_Mostly Animal-Based         0.490794
PhysicalActivities                   0.485412
LocalFoodFrequency                   0.469078
HomeSize                             0.451047
ClothingFrequency                    0.438675
SustainableBrands                    0.431190
DisposalMethods_Composting           0.382957
EnergySource_Mixed                   0.362023
Age                                  0.357638
DietType_Balanced                    0.328049
Gender_Female                        0.268883
TransportationMode_Public Transit    0.266944
TransportationMode_Bike              0.256567
DisposalMethods_Combination          0.255950
Gender_Male                          0.227619
Location_Suburban                    0.206984
Gender_Non-Binary                    0.102238
Location_Urban                       0.102033
HomeType_Apartment                   0.092934
Location_Rural                       0.088603
HomeType_House                       0.071909
Name: Rating, dtype: float64

Correlations for comparison

In [3]:
# you can compare to correlations too
df.corr(numeric_only=True)

,Age,LocalFoodFrequency,HomeSize,ClothingFrequency,SustainableBrands,EnvironmentalAwareness,CommunityInvolvement,MonthlyElectricityConsumption,MonthlyWaterConsumption,UsingPlasticProducts,...,EnergySource_Mixed,EnergySource_Non-Renewable,HomeType_Apartment,HomeType_House,Gender_Female,Gender_Male,Gender_Non-Binary,DisposalMethods_Combination,DisposalMethods_Composting,DisposalMethods_Landfill
Age,1.000000,-0.071496,0.226118,0.096458,-0.031730,-0.171008,0.018039,0.075677,0.098251,0.006506,...,0.014743,-0.013136,-0.105074,0.160521,-0.000770,-0.015259,0.013424,0.121774,-0.083922,0.037561
LocalFoodFrequency,-0.071496,1.000000,-0.095009,-0.470486,0.361120,0.428369,0.323344,-0.385273,-0.466142,-0.469295,...,-0.011488,-0.401579,0.025755,0.057100,0.256236,-0.265495,-0.039203,-0.007314,0.265087,-0.427469
HomeSize,0.226118,-0.095009,1.000000,0.085872,-0.052361,-0.160115,0.050863,0.173429,0.099701,-0.002091,...,0.051761,0.026896,-0.163524,0.316737,-0.045620,-0.069901,0.127367,0.137184,-0.092678,-0.017441
ClothingFrequency,0.096458,-0.470486,0.085872,1.000000,-0.316506,-0.456885,-0.345348,0.437818,0.407474,0.433236,...,0.043246,0.378334,0.025512,-0.044683,-0.328836,0.239180,0.111512,0.122323,-0.366523,0.384419
SustainableBrands,-0.031730,0.361120,-0.052361,-0.316506,1.000000,0.409117,0.191926,-0.471134,-0.295551,-0.392943,...,0.107354,-0.445764,-0.005565,0.111452,0.306072,-0.166008,-0.138148,0.137275,0.219627,-0.493123
EnvironmentalAwareness,-0.171008,0.428369,-0.160115,-0.456885,0.409117,1.000000,0.280353,-0.521972,-0.420940,-0.378163,...,-0.032419,-0.407376,-0.011362,0.032512,0.296553,-0.225015,-0.036609,0.040882,0.263885,-0.440708
CommunityInvolvement,0.018039,0.323344,0.050863,-0.345348,0.191926,0.280353,1.000000,-0.312021,-0.405170,-0.273487,...,-0.291963,-0.145746,-0.089522,0.092769,0.251714,-0.258530,0.003764,-0.272067,0.351382,-0.103566
MonthlyElectricityConsumption,0.075677,-0.385273,0.173429,0.437818,-0.471134,-0.521972,-0.312021,1.000000,0.509492,0.395151,...,0.086485,0.393762,0.049778,-0.067041,-0.334391,0.214455,0.080097,0.032020,-0.324934,0.345207
MonthlyWaterConsumption,0.098251,-0.466142,0.099701,0.407474,-0.295551,-0.420940,-0.405170,0.509492,1.000000,0.478874,...,0.053700,0.334158,-0.024051,0.024555,-0.287058,0.266703,0.009932,0.013122,-0.355150,0.443885
UsingPlasticProducts,0.006506,-0.469295,-0.002091,0.433236,-0.392943,-0.378163,-0.273487,0.395151,0.478874,1.000000,...,-0.078959,0.407734,0.094092,-0.121929,-0.365856,0.223926,0.181717,-0.131669,-0.455546,0.493631
PhysicalActivities,-0.067753,0.314831,-0.178462,-0.337750,0.305010,0.359014,0.401806,-0.421565,-0.435375,-0.388558,...,-0.245691,-0.232309,-0.019744,0.086170,0.276709,-0.205667,-0.092725,-0.220130,0.298189,-0.254074
Rating,-0.062691,0.506333,0.041610,-0.466973,0.512563,0.589104,0.412972,-0.571783,-0.557345,-0.575764,...,0.052122,-0.532261,-0.046101,0.044927,0.328322,-0.281732,-0.082908,0.054590,0.375585,-0.583396
Location_Rural,0.310291,-0.152972,0.142004,0.192426,-0.022976,-0.176681,-0.053547,0.141137,0.152044,0.050316,...,0.062136,0.107606,-0.215970,0.149129,0.025749,0.009424,-0.021636,0.303268,-0.171179,0.094287
Location_Suburban,-0.001489,0.132718,0.048345,-0.191204,0.145291,0.191225,0.166995,-0.115523,-0.097082,-0.068189,...,-0.048507,-0.183342,0.048457,0.075688,0.016413,-0.063533,0.043112,-0.167401,0.042361,-0.183199
Location_Urban,-0.293222,0.018556,-0.180996,-0.000186,-0.116888,-0.014786,-0.117412,-0.023733,-0.051696,0.017320,...,-0.012695,0.072852,0.158818,-0.213866,-0.040120,0.051704,-0.020612,-0.128162,0.122106,0.085362
DietType_Balanced,-0.116959,0.013896,-0.110610,0.015301,0.040776,-0.034752,-0.308014,0.010405,0.067450,0.132257,...,0.174924,-0.057365,0.154683,-0.096798,-0.026274,0.047540,-0.101029,0.031732,-0.112280,-0.159270
DietType_Mostly Animal-Based,0.018267,-0.298283,0.003789,0.355131,-0.442013,-0.306599,-0.060994,0.398928,0.294873,0.320957,...,-0.144314,0.385705,-0.001461,-0.086973,-0.282993,0.159309,0.151431,-0.158092,-0.202481,0.494213
TransportationMode_Bike,-0.009222,0.128607,-0.015598,-0.166960,0.106251,0.198538,0.005294,-0.183697,-0.109940,-0.151423,...,0.099010,-0.166021,-0.096756,0.043682,0.131292,-0.088301,0.046973,0.206075,0.189661,-0.204974
TransportationMode_Car,0.076302,-0.362853,0.027768,0.387320,-0.453746,-0.431475,-0.078304,0.369709,0.316652,0.407391,...,-0.199532,0.507409,-0.047653,-0.062394,-0.225485,0.155166,0.051707,-0.186083,-0.152658,0.539341
TransportationMode_Public Transit,-0.143470,0.098447,-0.061902,-0.095317,0.131996,0.060201,-0.147024,0.004537,0.005633,0.031255,...,0.183883,-0.226992,0.204587,-0.048544,-0.060745,0.006007,0.013040,-0.096421,-0.210528,-0.183373
EnergySource_Mixed,0.014743,-0.011488,0.051761,0.043246,0.107354,-0.032419,-0.291963,0.086485,0.053700,-0.078959,...,1.000000,-0.463081,0.025125,0.017695,-0.053215,0.063898,0.027522,0.353839,-0.195018,-0.240117
EnergySource_Non-Renewable,-0.013136,-0.401579,0.026896,0.378334,-0.445764,-0.407376,-0.145746,0.393762,0.334158,0.407734,...,-0.463081,1.000000,-0.015159,-0.108834,-0.294080,0.185801,0.098323,-0.137746,-0.148838,0.532379
HomeType_Apartment,-0.105074,0.025755,-0.163524,0.025512,-0.005565,-0.011362,-0.089522,0.049778,-0.024051,0.094092,...,0.025125,-0.015159,1.000000,-0.609945,-0.057147,-0.036057,0.060870,-0.071397,-0.050489,-0.089122
HomeType_House,0.160521,0.057100,0.316737,-0.044683,0.111452,0.032512,0.092769,-0.067041,0.024555,-0.121929,...,0.017695,-0.108834,-0.609945,1.000000,0.091184,-0.054027,0.021710,0.077080,-0.034047,-0.021666
Gender_Female,-0.000770,0.256236,-0.045620,-0.328836,0.306072,0.296553,0.251714,-0.334391,-0.287058,-0.365856,...,-0.053215,-0.294080,-0.057147,0.091184,1.000000,-0.523533,-0.312208,0.002379,0.211303,-0.228154
Gender_Male,-0.015259,-0.265495,-0.069901,0.239180,-0.166008,-0.225015,-0.258530,0.214455,0.266703,0.223926,...,0.063898,0.185801,-0.036057,-0.054027,-0.523533,1.000000,-0.324945,0.006675,-0.162426,0.207436
Gender_Non-Binary,0.013424,-0.039203,0.127367,0.111512,-0.138148,-0.036609,0.003764,0.080097,0.009932,0.181717,...,0.027522,0.098323,0.060870,0.021710,-0.312208,-0.324945,1.000000,-0.048934,-0.102221,0.073777
DisposalMethods_Combination,0.121774,-0.007314,0.137184,0.122323,0.137275,0.040882,-0.272067,0.032020,0.013122,-0.131669,...,0.353839,-0.137746,-0.071397,0.077080,0.002379,0.006675,-0.048934,1.000000,-0.267916,-0.292396
DisposalMethods_Composting,-0.083922,0.265087,-0.092678,-0.366523,0.219627,0.263885,0.351382,-0.324934,-0.355150,-0.455546,...,-0.195018,-0.148838,-0.050489,-0.034047,0.211303,-0.162426,-0.102221,-0.267916,1.000000,-0.360880
DisposalMethods_Landfill,0.037561,-0.427469,-0.017441,0.384419,-0.493123,-0.440708,-0.103566,0.345207,0.443885,0.493631,...,-0.240117,0.532379,-0.089122,-0.021666,-0.228154,0.207436,0.073777,-0.292396,-0.360880,1.000000

In [4]:
df.corr(numeric_only=True)['Rating'].sort_values(ascending=False)

Rating                               1.000000
EnvironmentalAwareness               0.589104
SustainableBrands                    0.512563
LocalFoodFrequency                   0.506333
PhysicalActivities                   0.478654
CommunityInvolvement                 0.412972
DisposalMethods_Composting           0.375585
Gender_Female                        0.328322
TransportationMode_Bike              0.224707
Location_Suburban                    0.186580
DisposalMethods_Combination          0.054590
EnergySource_Mixed                   0.052122
HomeType_House                       0.044927
HomeSize                             0.041610
TransportationMode_Public Transit    0.040284
DietType_Balanced                   -0.043269
HomeType_Apartment                  -0.046101
Age                                 -0.062691
Location_Urban                      -0.076609
Gender_Non-Binary                   -0.082908
Location_Rural                      -0.106905
Gender_Male                         -0.281732
ClothingFrequency                   -0.466973
DietType_Mostly Animal-Based        -0.498082
EnergySource_Non-Renewable          -0.532261
MonthlyWaterConsumption             -0.557345
MonthlyElectricityConsumption       -0.571783
UsingPlasticProducts                -0.575764
TransportationMode_Car              -0.580408
DisposalMethods_Landfill            -0.583396
Name: Rating, dtype: float64