### Phik-matrix -> Associations

Associations measure the strength of assocation between two variables. While correlations only measure LINEAR connection, associations can also handle non-linear connections. See "associations_vs_correlations.ipynb" for a simple comparison where associations are usually more useful.

**NOTE!** You can see both the correlations and associations at the asme time if you use SweetViz or Dython! You can also have correlations/phik-matrix in ydata at the same time, if you configure it correctly.

In [1]:
# if phik-matrix not found in pandas, try:
# pip install phik
import phik
import pandas as pd

# load data
df = pd.read_csv("../winequality-red.csv")

# compute phik-matrix values
phik_matrix = df.phik_matrix()

phik_matrix

interval columns not set, guessing: ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
fixed acidity,1.000000,0.321443,0.562141,0.229768,0.190932,0.161585,0.161312,0.800191,0.792807,0.197559,0.594446,0.189783
volatile acidity,0.321443,1.000000,0.448060,0.088084,0.157324,0.070250,0.184496,0.176478,0.296855,0.250486,0.310235,0.439844
citric acid,0.562141,0.448060,1.000000,0.288250,0.684409,0.239775,0.234207,0.336594,0.601202,0.576303,0.237058,0.295440
residual sugar,0.229768,0.088084,0.288250,1.000000,0.368995,0.565091,0.422196,0.521422,0.000000,0.000000,0.302003,0.142188
chlorides,0.190932,0.157324,0.684409,0.368995,1.000000,0.295494,0.112758,0.366272,0.406137,0.702763,0.296476,0.254780
free sulfur dioxide,0.161585,0.070250,0.239775,0.565091,0.295494,1.000000,0.555849,0.222223,0.098526,0.182611,0.135759,0.080553
total sulfur dioxide,0.161312,0.184496,0.234207,0.422196,0.112758,0.555849,1.000000,0.251383,0.140926,0.176662,0.252863,0.224657
density,0.800191,0.176478,0.336594,0.521422,0.366272,0.222223,0.251383,1.000000,0.514095,0.184517,0.696053,0.240927
pH,0.792807,0.296855,0.601202,0.000000,0.406137,0.098526,0.140926,0.514095,1.000000,0.378761,0.473712,0.134442
sulphates,0.197559,0.250486,0.576303,0.000000,0.702763,0.182611,0.176662,0.184517,0.378761,1.000000,0.204516,0.331899
alcohol,0.594446,0.310235,0.237058,0.302003,0.296476,0.135759,0.252863,0.696053,0.473712,0.204516,1.000000,0.446570
quality,0.189783,0.439844,0.295440,0.142188,0.254780,0.080553,0.224657,0.240927,0.134442,0.331899,0.446570,1.000000

In [2]:
phik_matrix['quality'].sort_values(ascending=False)

quality                 1.000000
alcohol                 0.446570
volatile acidity        0.439844
sulphates               0.331899
citric acid             0.295440
chlorides               0.254780
density                 0.240927
total sulfur dioxide    0.224657
fixed acidity           0.189783
residual sugar          0.142188
pH                      0.134442
free sulfur dioxide     0.080553
Name: quality, dtype: float64

Correlations for comparison

In [3]:
# you can compare to correlations too
df.corr(numeric_only=True)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
fixed acidity,1.000000,-0.256131,0.671703,0.114777,0.093705,-0.153794,-0.113181,0.668047,-0.682978,0.183006,-0.061668,0.124052
volatile acidity,-0.256131,1.000000,-0.552496,0.001918,0.061298,-0.010504,0.076470,0.022026,0.234937,-0.260987,-0.202288,-0.390558
citric acid,0.671703,-0.552496,1.000000,0.143577,0.203823,-0.060978,0.035533,0.364947,-0.541904,0.312770,0.109903,0.226373
residual sugar,0.114777,0.001918,0.143577,1.000000,0.055610,0.187049,0.203028,0.355283,-0.085652,0.005527,0.042075,0.013732
chlorides,0.093705,0.061298,0.203823,0.055610,1.000000,0.005562,0.047400,0.200632,-0.265026,0.371260,-0.221141,-0.128907
free sulfur dioxide,-0.153794,-0.010504,-0.060978,0.187049,0.005562,1.000000,0.667666,-0.021946,0.070377,0.051658,-0.069408,-0.050656
total sulfur dioxide,-0.113181,0.076470,0.035533,0.203028,0.047400,0.667666,1.000000,0.071269,-0.066495,0.042947,-0.205654,-0.185100
density,0.668047,0.022026,0.364947,0.355283,0.200632,-0.021946,0.071269,1.000000,-0.341699,0.148506,-0.496180,-0.174919
pH,-0.682978,0.234937,-0.541904,-0.085652,-0.265026,0.070377,-0.066495,-0.341699,1.000000,-0.196648,0.205633,-0.057731
sulphates,0.183006,-0.260987,0.312770,0.005527,0.371260,0.051658,0.042947,0.148506,-0.196648,1.000000,0.093595,0.251397
alcohol,-0.061668,-0.202288,0.109903,0.042075,-0.221141,-0.069408,-0.205654,-0.496180,0.205633,0.093595,1.000000,0.476166
quality,0.124052,-0.390558,0.226373,0.013732,-0.128907,-0.050656,-0.185100,-0.174919,-0.057731,0.251397,0.476166,1.000000

In [4]:
df.corr(numeric_only=True)['quality'].sort_values(ascending=False)

quality                 1.000000
alcohol                 0.476166
sulphates               0.251397
citric acid             0.226373
fixed acidity           0.124052
residual sugar          0.013732
free sulfur dioxide    -0.050656
pH                     -0.057731
chlorides              -0.128907
density                -0.174919
total sulfur dioxide   -0.185100
volatile acidity       -0.390558
Name: quality, dtype: float64