### Phik-matrix -> Associations

Associations measure the strength of assocation between two variables. While correlations only measure LINEAR connection, associations can also handle non-linear connections. See "associations_vs_correlations.ipynb" for a simple comparison where associations are usually more useful.

**NOTE!** You can see both the correlations and associations at the asme time if you use SweetViz or Dython! You can also have correlations/phik-matrix in ydata at the same time, if you configure it correctly.

In [1]:
# if phik-matrix not found in pandas, try:
# pip install phik
import phik
import pandas as pd

# load data
df = pd.read_csv("../houses_fixed.csv")

# compute phik-matrix values
phik_matrix = df.phik_matrix()

phik_matrix

interval columns not set, guessing: ['id', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long', 'sqft_living15', 'sqft_lot15']

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,1.000000,0.057917,0.071922,0.042775,0.079523,0.079736,0.083328,0.080466,0.007905,0.068590,...,0.112731,0.087144,0.061719,0.162603,0.036099,0.349753,0.265865,0.324206,0.118192,0.094621
date,0.057917,1.000000,0.000000,0.000000,0.218503,0.000000,0.117694,0.000000,0.000000,0.000000,...,0.046074,0.071037,0.000000,0.059099,0.051535,0.105657,0.089428,0.274107,0.132997,0.445935
price,0.071922,0.000000,1.000000,0.295426,0.741976,0.897678,0.039998,0.206170,0.418691,0.461042,...,0.655119,0.790851,0.792798,0.114610,0.166395,0.176781,0.340847,0.147703,0.543513,0.000000
bedrooms,0.042775,0.000000,0.295426,1.000000,0.513440,0.577934,0.000000,0.206289,0.000000,0.101675,...,0.372859,0.504386,0.358870,0.215240,0.016754,0.200912,0.110398,0.207712,0.439733,0.000000
bathrooms,0.079523,0.218503,0.741976,0.513440,1.000000,0.872038,0.078175,0.467907,0.132932,0.267578,...,0.716540,0.845564,0.730927,0.592173,0.077962,0.335261,0.245160,0.341409,0.613970,0.092823
sqft_living,0.079736,0.000000,0.897678,0.577934,0.872038,1.000000,0.099387,0.361306,0.182703,0.341497,...,0.751587,0.912003,0.915876,0.369898,0.092678,0.312896,0.210334,0.300795,0.744566,0.115169
sqft_lot,0.083328,0.117694,0.039998,0.000000,0.078175,0.099387,1.000000,0.036862,0.013989,0.069872,...,0.092050,0.131452,0.056421,0.075533,0.000000,0.086768,0.133683,0.170270,0.060134,0.627690
floors,0.080466,0.000000,0.206170,0.206289,0.467907,0.361306,0.036862,1.000000,0.030954,0.035377,...,0.371965,0.491357,0.226568,0.619898,0.082263,0.336160,0.248909,0.302391,0.340752,0.035294
waterfront,0.007905,0.000000,0.418691,0.000000,0.132932,0.182703,0.013989,0.030954,1.000000,0.487415,...,0.152552,0.107584,0.175473,0.043849,0.143569,0.103608,0.044216,0.125806,0.116409,0.000000
view,0.068590,0.000000,0.461042,0.101675,0.267578,0.341497,0.069872,0.035377,0.487415,1.000000,...,0.316487,0.211113,0.362660,0.101239,0.088816,0.175862,0.161999,0.200407,0.338905,0.057032
condition,0.071546,0.030876,0.055722,0.064260,0.301410,0.143798,0.068742,0.259440,0.013701,0.065927,...,0.345214,0.251134,0.222150,0.530487,0.055116,0.175571,0.137730,0.192261,0.148680,0.021595
grade,0.112731,0.046074,0.655119,0.372859,0.716540,0.751587,0.092050,0.371965,0.152552,0.316487,...,1.000000,0.759167,0.361175,0.498591,0.018985,0.323016,0.332405,0.295345,0.728762,0.079034
sqft_above,0.087144,0.071037,0.790851,0.504386,0.845564,0.912003,0.131452,0.491357,0.107584,0.211113,...,0.759167,1.000000,0.653433,0.498426,0.042127,0.405433,0.201088,0.391405,0.746974,0.152877
sqft_basement,0.061719,0.000000,0.792798,0.358870,0.730927,0.915876,0.056421,0.226568,0.175473,0.362660,...,0.361175,0.653433,1.000000,0.286798,0.100972,0.188781,0.157554,0.187746,0.384399,0.089360
yr_built,0.162603,0.059099,0.114610,0.215240,0.592173,0.369898,0.075533,0.619898,0.043849,0.101239,...,0.498591,0.498426,0.286798,1.000000,0.302272,0.619674,0.444881,0.541610,0.405671,0.064402
yr_renovated,0.036099,0.051535,0.166395,0.016754,0.077962,0.092678,0.000000,0.082263,0.143569,0.088816,...,0.018985,0.042127,0.100972,0.302272,1.000000,0.111430,0.076937,0.107714,0.000000,0.000000
zipcode,0.349753,0.105657,0.176781,0.200912,0.335261,0.312896,0.086768,0.336160,0.103608,0.175862,...,0.323016,0.405433,0.188781,0.619674,0.111430,1.000000,0.792253,0.785598,0.442037,0.112761
lat,0.265865,0.089428,0.340847,0.110398,0.245160,0.210334,0.133683,0.248909,0.044216,0.161999,...,0.332405,0.201088,0.157554,0.444881,0.076937,0.792253,1.000000,0.489357,0.284643,0.141580
long,0.324206,0.274107,0.147703,0.207712,0.341409,0.300795,0.170270,0.302391,0.125806,0.200407,...,0.295345,0.391405,0.187746,0.541610,0.107714,0.785598,0.489357,1.000000,0.432372,0.193991
sqft_living15,0.118192,0.132997,0.543513,0.439733,0.613970,0.744566,0.060134,0.340752,0.116409,0.338905,...,0.728762,0.746974,0.384399,0.405671,0.000000,0.442037,0.284643,0.432372,1.000000,0.085986
sqft_lot15,0.094621,0.445935,0.000000,0.000000,0.092823,0.115169,0.627690,0.035294,0.000000,0.057032,...,0.079034,0.152877,0.089360,0.064402,0.000000,0.112761,0.141580,0.193991,0.085986,1.000000

Correlations for comparison

In [2]:
# you can compare to correlations too
df.corr(numeric_only=True)

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,1.000000,-0.016762,0.001286,0.005160,-0.012258,-0.132109,0.018525,-0.002721,0.011592,-0.023783,0.008130,-0.010842,-0.005151,0.021380,-0.016907,-0.008224,-0.001891,0.020799,-0.002901,-0.138798
price,-0.016762,1.000000,0.308350,0.525138,0.702035,0.089661,0.256794,0.266369,0.397293,0.036362,0.667434,0.605567,0.323816,0.054012,0.126434,-0.053203,0.307003,0.021626,0.585379,0.082447
bedrooms,0.001286,0.308350,1.000000,0.515884,0.576671,0.031703,0.175429,-0.006582,0.079532,0.028472,0.356967,0.477600,0.303093,0.154178,0.018841,-0.152668,-0.008931,0.129473,0.391638,0.029244
bathrooms,0.005160,0.525138,0.515884,1.000000,0.754665,0.087740,0.500653,0.063744,0.187737,-0.124982,0.664983,0.685342,0.283770,0.506019,0.050739,-0.203866,0.024573,0.223042,0.568634,0.087175
sqft_living,-0.012258,0.702035,0.576671,0.754665,1.000000,0.172826,0.353949,0.103818,0.284611,-0.058753,0.762704,0.876597,0.435043,0.318049,0.055363,-0.199430,0.052529,0.240223,0.756420,0.183286
sqft_lot,-0.132109,0.089661,0.031703,0.087740,0.172826,1.000000,-0.005201,0.021604,0.074710,-0.008958,0.113621,0.183512,0.015286,0.053080,0.007644,-0.129574,-0.085683,0.229521,0.144608,0.718557
floors,0.018525,0.256794,0.175429,0.500653,0.353949,-0.005201,1.000000,0.023698,0.029444,-0.263768,0.458183,0.523885,-0.245705,0.489319,0.006338,-0.059121,0.049614,0.125419,0.279885,-0.011269
waterfront,-0.002721,0.266369,-0.006582,0.063744,0.103818,0.021604,0.023698,1.000000,0.401857,0.016653,0.082775,0.072075,0.080588,-0.026161,0.092885,0.030285,-0.014274,-0.041910,0.086463,0.030703
view,0.011592,0.397293,0.079532,0.187737,0.284611,0.074710,0.029444,0.401857,1.000000,0.045990,0.251321,0.167649,0.276947,-0.053440,0.103917,0.084827,0.006157,-0.078400,0.280439,0.072575
condition,-0.023783,0.036362,0.028472,-0.124982,-0.058753,-0.008958,-0.263768,0.016653,0.045990,1.000000,-0.144674,-0.158214,0.174105,-0.361417,-0.060618,0.003026,-0.014941,-0.106500,-0.092824,-0.003406
grade,0.008130,0.667434,0.356967,0.664983,0.762704,0.113621,0.458183,0.082775,0.251321,-0.144674,1.000000,0.755923,0.168392,0.446963,0.014414,-0.184862,0.114084,0.198372,0.713202,0.119248
sqft_above,-0.010842,0.605567,0.477600,0.685342,0.876597,0.183512,0.523885,0.072075,0.167649,-0.158214,0.755923,1.000000,-0.051943,0.423898,0.023285,-0.261190,-0.000816,0.343803,0.731870,0.194050
sqft_basement,-0.005151,0.323816,0.303093,0.283770,0.435043,0.015286,-0.245705,0.080588,0.276947,0.174105,0.168392,-0.051943,1.000000,-0.133124,0.071323,0.074845,0.110538,-0.144765,0.200355,0.017276
yr_built,0.021380,0.054012,0.154178,0.506019,0.318049,0.053080,0.489319,-0.026161,-0.053440,-0.361417,0.446963,0.423898,-0.133124,1.000000,-0.224874,-0.346869,-0.148122,0.409356,0.326229,0.070958
yr_renovated,-0.016907,0.126434,0.018841,0.050739,0.055363,0.007644,0.006338,0.092885,0.103917,-0.060618,0.014414,0.023285,0.071323,-0.224874,1.000000,0.064357,0.029398,-0.068372,-0.002673,0.007854
zipcode,-0.008224,-0.053203,-0.152668,-0.203866,-0.199430,-0.129574,-0.059121,0.030285,0.084827,0.003026,-0.184862,-0.261190,0.074845,-0.346869,0.064357,1.000000,0.267048,-0.564072,-0.279033,-0.147221
lat,-0.001891,0.307003,-0.008931,0.024573,0.052529,-0.085683,0.049614,-0.014274,0.006157,-0.014941,0.114084,-0.000816,0.110538,-0.148122,0.029398,0.267048,1.000000,-0.135512,0.048858,-0.086419
long,0.020799,0.021626,0.129473,0.223042,0.240223,0.229521,0.125419,-0.041910,-0.078400,-0.106500,0.198372,0.343803,-0.144765,0.409356,-0.068372,-0.564072,-0.135512,1.000000,0.334605,0.254451
sqft_living15,-0.002901,0.585379,0.391638,0.568634,0.756420,0.144608,0.279885,0.086463,0.280439,-0.092824,0.713202,0.731870,0.200355,0.326229,-0.002673,-0.279033,0.048858,0.334605,1.000000,0.183192
sqft_lot15,-0.138798,0.082447,0.029244,0.087175,0.183286,0.718557,-0.011269,0.030703,0.072575,-0.003406,0.119248,0.194050,0.017276,0.070958,0.007854,-0.147221,-0.086419,0.254451,0.183192,1.000000